import{a as b,i,S as v}from"./assets/vendor-u8rapaCG.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const u of t.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&r(u)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();async function h(s,o=1,n=15){const e=`https://pixabay.com/api/?key=46229228-83a12c4f45cb396a8637e93cb&q=${encodeURIComponent(s)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${n}`;try{return(await b.get(e)).data}catch(t){return console.error("Error:",t),{hits:[],totalHits:0}}}function y(s){const o=document.querySelector(".gallery"),n=s.map(r=>`<li class="gallery-item">
      <div class="info-container">
        <a href="${r.largeImageURL}" class="link">
          <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><span class="name-info">Likes</span> ${r.likes}</p>
          <p class="info-item"><span class="name-info">Views</span> ${r.views}</p>
          <p class="info-item"><span class="name-info">Comments</span> ${r.comments}</p>
          <p class="info-item"><span class="name-info">Downloads</span> ${r.downloads}</p>
        </div>
      </div>
    </li>`).join("");o.insertAdjacentHTML("beforeend",n)}const c=document.querySelector("#form-input"),l=document.querySelector(".gallery"),L=document.querySelector("#loadingId"),a=document.querySelector("#load-more");let f,m=1,d="";const g=15;a.classList.add("hidden");a.addEventListener("click",async()=>{m++,w();try{const{hits:s,totalHits:o}=await h(d,m,g);if(p(),s.length===0)i.error({message:"Sorry, there are no more images to load.",position:"topCenter"}),a.classList.add("hidden");else{y(s),S();const{height:n}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:n*2,behavior:"smooth"}),document.querySelectorAll(".gallery-item").length>=o&&(a.classList.add("hidden"),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topCenter"}))}}catch{p(),i.error({message:"Something went wrong, please try again later.",position:"topCenter"})}});c.addEventListener("submit",async s=>{if(s.preventDefault(),d=document.querySelector('input[name="Search"]').value.trim(),d===""){i.error({message:"Please enter a search term.",position:"topCenter"}),l.innerHTML="",c.reset();return}m=1,l.innerHTML="",w();try{const{hits:o,totalHits:n}=await h(d,m,g);p(),o.length===0?(i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"}),l.innerHTML="",c.reset(),a.classList.add("hidden")):(y(o),S(),n>g?a.classList.remove("hidden"):a.classList.add("hidden"))}catch{p(),i.error({message:"Something went wrong, please try again later.",position:"topCenter"}),l.innerHTML="",c.reset()}});function w(){L.classList.remove("hidden")}function p(){L.classList.add("hidden")}function S(){f&&f.destroy(),f=new v(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250})}
//# sourceMappingURL=index.js.map
